// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/branches": {
            "post": {
                "description": "Endpoint to create a new branch for a business. Requires branch details in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Branches"
                ],
                "summary": "Create a new branch",
                "parameters": [
                    {
                        "description": "Branch data",
                        "name": "branch",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateBranch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "request.ConversionFactor": {
            "type": "object",
            "properties": {
                "cashback_por_unidad": {
                    "type": "number"
                },
                "puntos_por_unidad": {
                    "type": "number"
                },
                "valor_minimo": {
                    "type": "number"
                }
            }
        },
        "request.CreateBranch": {
            "type": "object",
            "properties": {
                "nit_empresa": {
                    "type": "integer"
                },
                "nombre_sucursal": {
                    "type": "string"
                },
                "valor_conversion": {
                    "$ref": "#/definitions/request.ConversionFactor"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:6060",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Tag Service API",
	Description:      "A Tag service API in Go using Gin Framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
