basePath: /api
definitions:
  request.ConversionFactor:
    properties:
      cashback_por_unidad:
        type: number
      puntos_por_unidad:
        type: number
      valor_minimo:
        type: number
    type: object
  request.CreateBranch:
    properties:
      nit_empresa:
        type: integer
      nombre_sucursal:
        type: string
      valor_conversion:
        $ref: '#/definitions/request.ConversionFactor'
    type: object
host: localhost:6060
info:
  contact: {}
  description: A Tag service API in Go using Gin Framework
  title: Tag Service API
  version: "1.0"
paths:
  /branches:
    post:
      consumes:
      - application/json
      description: Endpoint to create a new branch for a business. Requires branch
        details in the request body.
      parameters:
      - description: Branch data
        in: body
        name: branch
        required: true
        schema:
          $ref: '#/definitions/request.CreateBranch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create a new branch
      tags:
      - Branches
swagger: "2.0"
